# Jekyll configuration for Ultracube Factoriopedia

# Include JSON files in the build output
include:
  - "*.json"
  - "icons/*.json"

# Exclude unnecessary files from the build
exclude:
  - README.md

# Keep files that would normally be excluded
keep_files:
  - "ultracube_organized_data.json"
  - "ultracube_organized_data_backup.json"
  - "icons/icon_mapping.json"