# Jekyll configuration for Ultracube Factoriopedia

# Set the source directory to webpage
source: webpage

# Include JSON files in the build output
include:
  - "*.js"
  - "*.css"
  - "*.json"
  - "icons/*.json"
  - "icons/*.png"

# Exclude unnecessary files from the build
exclude:
  - README.md
  - .git/
  - .github/

# Keep files that would normally be excluded
keep_files:
  - "ultracube_organized_data.json"
  - "ultracube_organized_data_backup.json"
  - "icons/icon_mapping.json"